// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETD_Lab5.Models;

namespace NETD_Lab5.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20201205233441_AddAll1")]
    partial class AddAll1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NETD_Lab5.Models.Author", b =>
                {
                    b.Property<int>("authorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("yob")
                        .HasColumnType("int");

                    b.HasKey("authorID");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("NETD_Lab5.Models.Book", b =>
                {
                    b.Property<int>("bookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ISBN")
                        .HasColumnType("int");

                    b.Property<string>("author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("copies")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("version")
                        .HasColumnType("int");

                    b.HasKey("bookID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("NETD_Lab5.Models.BookAuthor", b =>
                {
                    b.Property<int>("bookID")
                        .HasColumnType("int");

                    b.Property<int>("authorID")
                        .HasColumnType("int");

                    b.HasKey("bookID", "authorID");

                    b.HasIndex("authorID");

                    b.ToTable("BookAuthor");
                });

            modelBuilder.Entity("NETD_Lab5.Models.Dvd", b =>
                {
                    b.Property<int>("dvdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ASIN")
                        .HasColumnType("int");

                    b.Property<string>("actor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("copies")
                        .HasColumnType("int");

                    b.Property<string>("director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dvdID");

                    b.ToTable("Dvds");
                });

            modelBuilder.Entity("NETD_Lab5.Models.BookAuthor", b =>
                {
                    b.HasOne("NETD_Lab5.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("authorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NETD_Lab5.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("bookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
